### ISSUE TITLE
이슈&PR 템플릿 추가

### ISSUE THREAD

**Issue by dode777** [Doong-Ji/cola-map#1]
전 프로젝트에서 사용했던 것처럼
템플릿을 만들고 적용할 필요가 있을 것 같아요

**Comment by HANYUNSEONG** [comment]
저번 클론 프로젝트에서 사용하시던 템플릿 가져다가 사용해도 괜찮을 것 같아요!

**Comment by dode777** [comment]
> 저번 클론 프로젝트에서 사용하시던 템플릿 가져다가 사용해도 괜찮을 것 같아요!

답이 늦었습니다! 네 그렇게 하도록 할게요!

**Comment by dode777** [comment]
추가했습니다. 이슈 닫습니다.
