### ISSUE TITLE
프론트엔드 개발환경을 세팅한다

### ISSUE THREAD

**Issue by junh0328** [Doong-Ji/cola-map#3]
# Pagination

### 개인 페이지

# 컴포넌트 라이브러리

- react + react-router-dom

# 상태관리

- redux
- redux-saga
- redux-devtools

# API

- kakao apis

## 디자인 라이브러리

- emotion
- ant-design

## 미디어 쿼리

- Mobile : min 481, max 840
- Tablet : min 841, max 1280
- smallPC : min 1281, max 1600
- widePC : min 1601, max 1920
- widerPC : min 1921px

> 모바일로 먼저 구성 후에, 태블릿 > PC 순으로 확장 예정

**Comment by junh0328** [comment]
📁 sagas/map 에서 기존 useEffect(()=> { FetchingMap() }) 함수를 호출하는 부분에서 다음과 같은 에러가 발생하여 setTimeout 콜백으로 잠시 가둬두었습니다.

```js
function* fetchMap() {
  try {
    setTimeout(() => {
      FetchingMap();
    }, 1000);
    yield put({
      type: FETCH_MAP_SUCCESS,
    });
  } catch (err) {
    console.log(err);
    yield put({
      type: FETCH_MAP_FAILURE,
      error: err.response,
    });
  }
}
```

<a href="https://www.google.com/search?q=cannot+read+property+%27currentstyle%27+of+null&rlz=1C5CHFA_enKR920KR920&hl=ko&sxsrf=ALeKk02lhslitCBXeAQl2wUSldLZxnLX5A%3A1620907831531&source=hp&ei=NxedYKflHazxhwORs7-QBg&iflsig=AINFCbYAAAAAYJ0lR4qjJQ7z3g6FfJJMrN6lQS-4ThQh&oq=&gs_lcp=Cgdnd3Mtd2l6EAEYATIHCCMQ6gIQJzIHCCMQ6gIQJzIHCCMQ6gIQJzIHCCMQ6gIQJzIHCCMQ6gIQJzIHCCMQ6gIQJzIHCCMQ6gIQJzIHCCMQ6gIQJzIHCCMQ6gIQJ1AAWABgpBJoAXAAeACAAQCIAQCSAQCYAQCqAQdnd3Mtd2l6sAEJ&sclient=gws-wiz">cannot read property 'currentstyle' of null</a> 해당 오류가 발생하네요..

setTimeout() 으로 묶은 콜백만 푸시면 보실 수 있을 것 같습니다.

**Comment by junh0328** [comment]
> 해당 에러입니다.

<img width="353" alt="스크린샷 2021-05-13 오후 9 14 00" src="https://user-images.githubusercontent.com/54658162/118124157-278e5000-b430-11eb-9520-06bf5b26f3cb.png">

비동기로 담는데, <div id="map"> 보다 해당 스크립트와 함수가 더 먼저 생성되어 생기는 문제라고 링크를 통해 구글링해 본 결과 window.onload 함수로 스크립트 태그를 묶어 주라고 하는데 도통 이해가 안되네요..

setTimeout 콜백으로 담아두면 실행은 되나 원하는 결과로 상태관리가 되지는 않는듯 합니다 ㅠㅠ

**Comment by HANYUNSEONG** [comment]
```js
const container = document.getElementById('Map');
const options = {
  center: new kakao.maps.LatLng(37.40209297146093, 127.1086502555068), // 카카오 판교 오피스 주소
  level: 3,
};
console.log(container); // null
const map = new kakao.maps.Map(container, options); // Error
```
아직 생성되지 않은 엘리먼트에 접근하기 때문에 container는 null을 가지고 있어서 생긴 문제입니다.

window.onload로 감싸서 요소들이 로드되었을 때 실행을 해야 정상적으로 지도가 출력됩니다!
```js
window.onload = function() { 
  const container = document.getElementById('Map');
  const options = {
    center: new kakao.maps.LatLng(37.40209297146093, 127.1086502555068), // 카카오 판교 오피스 주소
    level: 3,
  };
  console.log(container); // <div id="Map">
  const map = new kakao.maps.Map(container, options); // Success
}
```

**Comment by junh0328** [comment]
오 여기서 군요,, 감사합니다 !! 수정해서 내일 pr 올리도록 하겠습니다 ^^7

**Comment by HANYUNSEONG** [comment]
네넵 세팅하시느라 고생이 많으십니다🙌🙌

**Comment by HANYUNSEONG** [comment]
앗 App.js에서 AppLayout 부분 잘못 수정했습니다 저 부분 빼고 보시면 될 것 같아요!
