### ISSUE TITLE
콜라맵 (가게 제보, 개인)

### ISSUE THREAD

**Issue by HANYUNSEONG** [Doong-Ji/cola-map#6]
## 콜라맵에 가게 제보 페이지와 개인 페이지를 만든다.
- Report
- Private

### 가게 제보 (Report)
- [x] 위치를 찍어서 가게 제보 (가게 이름, 음료 종류를 포함한 모달)
- [x] 지도 중심의 좌표를 받아서 주소로 변환 후 표시하는 컴포넌트 생성

### 개인 페이지 (Private)
- [x] 본인이 제보한 가게 리스트
- [x] 내가 쓴 리뷰
- [x] 자주 묻는 질문
- [x] 문의 사항
- [x] 회원 탈퇴
- [x] 로그아웃

**Comment by junh0328** [comment]
윤성님 제가 커밋할 때 feature 번호를 잘못보고 6으로 했는데, git reset HEAD^는 시켜놨습니다.... 글씨는 남겠네요 죄송합니다 ㅠㅠ
