### ISSUE TITLE
🐣 [FEATURE] 검색 결과 리스트 가져오기

### ISSUE THREAD

**Issue by junh0328** [Doong-Ji/cola-map#8]
## 📄 이슈 내용
- 위치 검색 시에 결과물을 `<SearchModal>` 컴포넌트에서 보여줄 수 있도록 한다

## 📝 상세 내용
- <a href="https://apis.map.kakao.com/web/sample/keywordList/">키워드로 장소검색하고 목록으로 표출하기</a>에서 주는 sdk를 뜯어, 우리가 입력하는 값(e.target.value)에 대한 결과 목록을 불러올 수 있도록 만든다

## ✔ 체크리스트
- [x] 데이터가 정상적으로 요청을 보내는지
- [x] 결과물 배열을 확인할 수 있는지
- [x] 클릭을 통해 `<Map>`컴포넌트에 표현할 수 있는지

## 📍 레퍼런스
- <a href="https://apis.map.kakao.com/web/documentation/#services_Places_keywordSearch">카카오 맵 api, keywordSearch 함수</a>
- <a href="https://apis.map.kakao.com/web/sample/keywordList/">카카오 맵 api, 키워드로 장소 검색하고 목록으로 표출하기</a>
- <a href="https://developers.kakao.com/docs/latest/ko/local/dev-guide#search-by-keyword">카카오 맵 개발 가이드 (쿼리문 요청 <-> 결과)</a>

**Comment by HANYUNSEONG** [comment]
- useGetList.js
```js
function getSearchData(keyword) {
  return new Promise((resolve) => {
    ps.keywordSearch(keyword, (data, status) => {
      resolve(data);
    });
  });
}

return {
  getSearchData,
};
```

- SearchInput
```js
const onChangeValue = useCallback((e) => {
  setSearchValue(e.target.value);
  if (e.target.value !== '') {
    (async () => {
      await getSearchData(e.target.value).then((result) => {
        console.log(result);
      });
    })();
  }
  // fetch(e.target.value);
}, []);
```

이렇게 하시면 키워드로 검색해서 나온 결과 값 넘어옵니다!

**Comment by junh0328** [comment]
앗 이른 아침부터 감사합니다 윤성님 확인해보고 수정뒤에 기능 구현 완료해서 pr 올리도록 하겠습니다!

**Comment by HANYUNSEONG** [comment]
네넵!

**Comment by junh0328** [comment]
추가적으로 <a href="https://www.notion.so/CRA-25f56e1831604154acf5885cb5309f5f">절대경로 설정</a> 관련해서 윤성님과 협의 후에 정하면 될 것 같습니다. 자잘한 주석 줄이는 것, 후에 상의후 할 리팩토링 외에는 코드 및 과제는 완료하였습니다.
